version: "3"

services:

  database:
    container_name: "postgres"
    image: postgres:12.1
    ports: 
    - "5434:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ong
    networks: 
      - app-network
    restart: always

  backend:
    container_name: "laravel"
    build: ./backend
    ports: 
      - "8080:80"
    depends_on: 
      - database
    networks: 
      - app-network

    restart: always

  frontend:
    container_name: "vue"
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always

networks: 
  app-network:
    driver: bridge
  

